### ISSUE TITLE
joy-histograms for discrete data

### ISSUE THREAD

**Issue by noamross** [clauswilke/ggjoy#10]
Excellent work with this package!  I wonder if you would be inclined to add a new geom using histograms rather than density plots, especially for discrete data such as Likert scale measures.

I like to make "outlined" histograms like so:

``` r
library(ggplot2)
bw = 1000
ggplot(diamonds, aes(x=price)) +
  geom_histogram(binwidth=bw, fill="white", col=NA) +
  geom_step(aes(y=..count..), stat="bin", binwidth=bw,
            position=position_nudge(x=-bw/2), pad=TRUE)
```

![](http://i.imgur.com/3rd17GL.png)

It would be great to be able to stack these like joyplots.

**Comment by clauswilke** [comment]
I think this would be a good addition, but I'll likely not get around to do it anytime soon. Should be straightforward, though. The easiest would be to convert the count data into ridgelines and then draw with `geom_ridgeline`. The code would be very similar to the current `geom_joy`, just with some changes in the `setup_data` function in lines 312-356 [here.](https://github.com/clauswilke/ggjoy/blob/master/R/geoms.R) (In case you want to take a stab.)

Alternatively, one could write a `stat_histogram_curve` that creates a histogram step function as output, and use that directly with `geom_joy`. Upon further reflection, maybe the better strategy.

**Comment by noamross** [comment]
I think the latter strategy makes sense, as well. If I have time I'll give it a shot.

**Comment by clauswilke** [comment]
I think the strategy would have to be to inherit from `stat_bin`, reimplement `compute_group`, call the `compute_group` function of `stat_bin` for the heavy lifting, and then just convert the bins + heights into a step function. Shouldn't be that difficult.

**Comment by clauswilke** [comment]
FYI, I've got this working now in my local repository. Will push once I've got proper internet access again, likely some time next week.

However, stacking histograms doesn't look so good, because the bars tend to overlap exactly, and this results in strange visual effects. Non-overlapping histograms (`scale < 1`) may be useful, though.

**Comment by clauswilke** [comment]
Ok, I managed to push. Install the latest version from github and do `?stat_binline` for examples.

**Comment by noamross** [comment]
Very nice!  I think the best application for this is actual count data, like so:

```
count_data <- data.frame(group = rep(letters[1:5], each=20),
                         mean = rep(1:5, each=20))
count_data$count = rpois(nrow(count_data), count_data$mean)
ggplot(count_data, aes(x=count, y=group, fill=group)) +
  geom_joy(stat="binline", binwidth=1, scale=0.9)
```
<img width="582" alt="screen shot 2017-07-21 at 10 25 25 am" src="https://user-images.githubusercontent.com/571752/28467780-f42f5f4a-6dfe-11e7-958a-4b2878b19852.png">
