### ISSUE TITLE
use density plots from ggs_density?

### ISSUE THREAD

**Issue by Kelsman28** [clauswilke/ggjoy#11]
Hello, I realize your package is brand new but I was wondering how easy/hard it would be to use density plots created by ggs_density with geom_joy?  I am creating many density plots from ggs objects that I use to create density plots of my mcmc chains (see example figure).

ggfin <- ggs(fin)
p = ggs_density(ggfin, family = "beta1mu")
p + theme_classic()+
      labs(x=expression(bold(Bottle~k["Terr Stream T34"]~" "~Day^{-1})))+
    ylab("Probability Density") 

![primealgae_darkstr_k1_t234fin](https://user-images.githubusercontent.com/6495798/28340344-a8595078-6bcc-11e7-903a-7ed75a4cc47a.jpg)

**Comment by clauswilke** [comment]
This is trivially possible alredy. The how is left as an exercise to the reader.

Hint: take a look at what `ggfin` in your example actually is, or take a look at the `ggs_density` [source code.](https://github.com/xfim/ggmcmc/blob/master/R/ggs_density.R)
