### ISSUE TITLE
R >= 3.3 ?

### ISSUE THREAD

**Issue by jonathon-love** [clauswilke/ggjoy#19]
hi,

we're loving ggjoy, and have made use of it in the descriptives for jamovi (www.jamovi.org), however in the most recent version you've bumped it to require R >= 3.3

this makes it tricky for us, because we provide jamovi for ubuntu xenial (+mint, etc.) and these only ship with R 3.2. my solution is normally to just patch whatever package back to R >= 3.2, and ship that with jamovi, but that's less than ideal.

anyhow, just wondering what prompted the change.

with thanks

**Comment by clauswilke** [comment]
It was `R (>= 3.3.0)` from the [very first commit](https://github.com/clauswilke/ggjoy/blob/cd4b41d0e29a70e83c824479ac576aa7d5f8ab75/DESCRIPTION). This is simply because I don't have R 3.2 around anymore and have no idea whether things would work or not.

**Comment by jonathon-love** [comment]
I gather you're not interested in supporting 3.2?

I'd be 99.9% confident it would *just work* on 3.2. we certainly haven't had any issues.

with thanks

**Comment by clauswilke** [comment]
I'm not opposed to changing the requirement to R 3.2 if it helps you. Please submit a pull request.

Just know that I won't submit a new version of ggjoy to CRAN anytime soon, I already annoyed them when I submitted my last update. (Because I submitted too many updates in a short time.)
