### ISSUE TITLE
do not display colours in example

### ISSUE THREAD

**Issue by likelet** [clauswilke/ggjoy#2]
all density plot in joy theme were displayed in gray, and the colour cannot be changed using _scale_fill_manual_ 
here is my session info
`Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Asia/Shanghai               
 date     2017-07-12                  

Packages --------------------------------------------------------------------------------------
 package    * version date       source                           
 colorspace   1.3-2   2016-12-14 CRAN (R 3.3.2)                   
 curl         2.3     2016-11-24 CRAN (R 3.3.2)                   
 devtools   * 1.12.0  2016-12-05 CRAN (R 3.3.2)                   
 digest       0.6.12  2017-01-27 cran (@0.6.12)                   
 ggjoy      * 0.1     2017-07-12 Github (clauswilke/ggjoy@3402761)
 ggplot2    * 2.2.1   2016-12-30 cran (@2.2.1)                    
 git2r        0.16.0  2016-11-20 CRAN (R 3.3.2)                   
 gtable       0.2.0   2016-02-26 CRAN (R 3.3.2)                   
 httr         1.2.1   2016-07-03 CRAN (R 3.3.2)                   
 labeling     0.3     2014-08-23 CRAN (R 3.3.2)                   
 lazyeval     0.2.0   2016-06-12 cran (@0.2.0)                    
 memoise      1.0.0   2016-01-29 CRAN (R 3.3.2)                   
 munsell      0.4.3   2016-02-13 CRAN (R 3.3.2)                   
 plyr         1.8.4   2016-06-08 CRAN (R 3.3.2)                   
 R6           2.2.0   2016-10-05 cran (@2.2.0)                    
 Rcpp         0.12.11 2017-05-22 cran (@0.12.11)                  
 rlang        0.1.1   2017-05-18 cran (@0.1.1)                    
 scales       0.4.1   2016-11-09 CRAN (R 3.2.3)                   
 tibble       1.3.3   2017-05-28 cran (@1.3.3)                    
 withr        1.0.2   2016-06-20 CRAN (R 3.3.2) `

**Comment by clauswilke** [comment]
Without specific code that causes an error this is not a useful issue. I suspect you made a mistake in your code. Coloring the areas works just fine, as shown in the 3rd example for `geom_joy()`:

    ggplot(diamonds, aes(x=price, y=cut, fill=cut, height=..density..)) +
      geom_joy(scale=4) +
      scale_y_discrete(expand=c(0.01, 0)) +
      scale_x_continuous(expand=c(0.01, 0)) +
      scale_fill_brewer(palette = 4) +
      theme_joy() + theme(legend.position="none")

<img width="688" alt="screen shot 2017-07-12 at 8 11 22 pm" src="https://user-images.githubusercontent.com/4210929/28132843-55f0793e-673e-11e7-8e65-9fd41fa77274.png">
