### ISSUE TITLE
color quantiles 

### ISSUE THREAD

**Issue by mstetter** [clauswilke/ggjoy#20]
I really enjoy plotting things with ggjoy. coloring quantiles is really a nice feature, but unfortunately I can't make it work. 

When I add the quantile function I get the error:

`Error in f(..., self = self) : Aesthetics can not vary along a ridgeline`

it works without the fill.

I am not sure what I am doing wrong or if my data is not the way it should be.

Here is my function.
`ggplot(data = p_joy1,aes(x = p,y=as.factor(generation),fill=as.factor(..quantile..))) + 
  geom_joy(calc_ecdf =TRUE,quantiles = c(0.2,0.8)) +
  scale_fill_manual(name= 'test',values = c('red','grey','blue'))+
  scale_y_discrete(expand = c(0.01,0)) +
  theme_joy()`

**Comment by clauswilke** [comment]
You need to use `geom_joy_gradient()`. Coloring by quantiles depends on some ugly hacks that I don't want to put into the regular `geom_joy()` function.

**Comment by mstetter** [comment]
Thanks a lot. Sorry for the confusion. Great package.
