### ISSUE TITLE
possible to drop purrr dependency?

### ISSUE THREAD

**Issue by jonathon-love** [clauswilke/ggjoy#21]
hi,

i notice that `ggjoy` imports `purrr`, which in turn imports:

`magrittr`
`tibble`
`rlang`
`Rcpp`

this is in order to user `purrr::reduce`, which is only used in one place.

would you consider replacing this `purrr::reduce()` call? or accepting a PR to replace it?

reducing the number of imports ggjoy uses would improve the situation for us.

with thanks

**Comment by clauswilke** [comment]
Yes, please submit a pull request. I agree with reducing mandatory dependencies as much as possible, I just find writing code in base R cumbersome so sometimes I take a shortcut to get the result I need. While you're at it, feel free to change the R version requirement. I'll likely submit a new ggjoy version to CRAN soon after all, b/c I added a new geom.

**Comment by jonathon-love** [comment]
sooo, about this new release? :)

**Comment by clauswilke** [comment]
There's a complication. I've been strongly encouraged to change the name of the package and of the key functions, due to the [awkward etymology](https://en.wikipedia.org/wiki/House_of_Dolls) of the name. I agree with this but haven't found the time to make the necessary changes.

**Comment by jonathon-love** [comment]
yeah, righto. you don't want to push an update as an interim measure?

you could mention in the description that there will be a name change soon.

with thanks

**Comment by clauswilke** [comment]
No, it would be better to just push through and do the renaming. Maybe I can get that done within a week or so.

**Comment by clauswilke** [comment]
This seems to work (vignettes build, passes CRAN check):
https://github.com/clauswilke/ggridges

Documentation still needs some fixing. I would appreciate if you could stress-test it.

**Comment by jonathon-love** [comment]
yup, i'll take a look. did you just do a find and replace?:

> The name "ridgeline plot" was proposed by Jenny Bryan on Twitter on April 24, 2017

**Comment by clauswilke** [comment]
Yes, I did. That's why I said "documentation still needs some fixing". I think I've caught all such cases now, but I haven't done a careful proofread yet.

Feel free to submit pull requests for any remaining such issues you find.

**Comment by clauswilke** [comment]
This exists now:
https://cran.r-project.org/web/packages/ggridges/index.html

Please don't advertise yet, I'm going to make a proper announcement within the next few days.

**Comment by jonathon-love** [comment]
oh great. it being on CRAN makes it much easier for it to slip into our build/testing pipeline.

with thanks

**Comment by jonathon-love** [comment]
i've run it through our tests, and everything seems fine. you're probably aware, but you're failing a few of yours:

https://cran.r-project.org/web/checks/check_results_ggridges.html

**Comment by clauswilke** [comment]
Those are the vdiffr tests, which are platform dependent. They all pass on my machine. It's strange that they would be run in the first place, they should be skipped on a different platform.

**Comment by clauswilke** [comment]
The new package is now officially announced:
http://serialmentor.com/blog/2017/9/15/goodbye-joyplots

I also fixed the build errors on CRAN.
