### ISSUE TITLE
Error in factor(quantile) : object 'quantile' not found

### ISSUE THREAD

**Issue by isezen** [clauswilke/ggjoy#23]
I want to use `stat = "density"` instead of `stat = "joy"` with `geom_joy_gradient` but I get the following error. What should I do?

```
ggplot(iris, aes(x=Sepal.Length, y=Species, fill=factor(..quantile..), height = ..density..)) +
+   geom_joy_gradient(stat = "density", calc_ecdf = TRUE, quantiles = c(0.05, 0.95)) +
+   scale_fill_manual(name = "Probability\nranges",
+                     values = c("red", "grey80", "blue")) +
+   theme_joy() + scale_y_discrete(expand = c(0.01, 0))
```

> Warning: Ignoring unknown parameters: calc_ecdf, quantiles
> Error in factor(quantile) : object 'quantile' not found

**EDIT 1:** 
My main concern is;
You mentioned `stat_joy` calculates densities different than `stat_density` in the documentation. 
I want to show the quantiles and maximum density value in a table. So, I need the densities calculated by `stat_joy`. Can you show a mini-example how to calculate densities as in `stat_joy`?

**EDIT 2:**
Claus said [[1](https://twitter.com/ClausWilke/status/897458872788672512)] that;
> You're trying to get stat_density something to do it can't, namely calculating quantiles. See the warning "Ignoring unkown parameters..."? That's stat_density telling you it doesn't understand what you want.

Isn't that possible to have the same functionality also for `stat = "density"`? (A feature request may be?)

**Comment by clauswilke** [comment]
`stat_density` is not part of this package, it's in ggplot2. You could open a feature request there, but I doubt they'll accept it. The feature is a bit hacky.

R has standalone functions to calculate densities and quantiles, you can always calculate them the way you want and then feed into ggplot2 (or print in a table).
