### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by stevelizcano** [clauswilke/ggjoy#4]
When installing from the installation command on R 3.4, the following fatal error occurs:

* installing *source* package ‘ggjoy’ ...
** R
Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from '/tmp/Rtmp724pj3/devtools36d870e81c1b/clauswilke-ggjoy-bab95c7/R':
  stats.R
ERROR: unable to collate and parse R files for package ‘ggjoy’

**Comment by jimmylovestea** [comment]
I had a similar problem. Updating the `devtools` package seemed to solve it.

**Comment by clauswilke** [comment]
I forgot to add a file earler. Should be fixed now.
