### ISSUE TITLE
Plotting geom_ridgeline() negative values

### ISSUE THREAD

**Issue by jakepog** [clauswilke/ggjoy#5]
Can geom_ridgeline() plot negative height values? 

![rplot02](https://user-images.githubusercontent.com/773223/28193333-1c5b441e-687f-11e7-8a13-8b0d266746a1.png)
![rplot01](https://user-images.githubusercontent.com/773223/28193332-1c587996-687f-11e7-8a4f-b28bab181a0f.png)

**Comment by clauswilke** [comment]
It can, but you have to set a negative value for `min_height`. By default it's set to zero.

**Comment by jakepog** [comment]
Ahh, looks good! Thank you. 

![rplot](https://user-images.githubusercontent.com/773223/28193815-0fe86848-6883-11e7-8c6b-22b674c2a9ae.png)
