### ISSUE TITLE
Help plotting density curves

### ISSUE THREAD

**Issue by ggdaniel** [clauswilke/ggjoy#6]
I want to plot a density curve instead of a line graph for each of my series. I know this isn't an "issue" persay, I would love any help you might be able to give.

Love the package!

**Comment by clauswilke** [comment]
I don't understand this request. Isn't that exactly what `geom_joy()` does? Can you elaborate what you mean by "density curve", or maybe provide a mockup, or a figure with just one density curve?

**Comment by ggdaniel** [comment]
My apologies for the lack of articulation. Upon further reflection, it looks like my issue is aesthetic. I cannot find the right adjustments to `scale` and `bandwidth`to make my joy plot correspond to the individual density plots created using `geom_line(stat = "density")`.  I have attached the code I wrote below. The two data sets are named differently but contain the same values.

I hope that helps and understand it still not make sense.

# Joy Plot
ggplot(cr_10to14, aes(x = cr, y = event_year, group = event_year, fill = event_year)) + 
    geom_joy(scale = 20, bandwidth = 0.0015) + 
    theme_joy() +
    coord_cartesian(xlim = c(0, .08)) + 
    scale_fill_manual(values = ocean_pal)

![image](https://user-images.githubusercontent.com/30167408/28224472-3a041892-689d-11e7-8984-8185171aaa1a.png)


# Individual Density Plots
 p <- ggplot(cr)
 p + geom_density(aes(x = cr$`2010`)) + ggtitle(2010) + xlab("catch (tons) / hook (hundreds)")
 p + geom_density(aes(x = cr$`2011`)) + ggtitle(2011) + xlab("catch (tons) / hook (hundreds)")
 p + geom_density(aes(x = cr$`2012`)) + ggtitle(2012) + xlab("catch (tons) / hook (hundreds)")
 p + geom_density(aes(x = cr$`2013`)) + ggtitle(2013) + xlab("catch (tons) / hook (hundreds)")
 p + geom_density(aes(x = cr$`2014`)) + ggtitle(2014) + xlab("catch (tons) / hook (hundreds)")

![2014](https://user-images.githubusercontent.com/30167408/28224512-5a5a27f8-689d-11e7-971a-280755e24eda.png)
![2013](https://user-images.githubusercontent.com/30167408/28224511-5a427504-689d-11e7-8bd7-471c06e3d21d.png)
![2012](https://user-images.githubusercontent.com/30167408/28224509-5a3db01e-689d-11e7-820a-ed67e6645b20.png)
![2011](https://user-images.githubusercontent.com/30167408/28224508-5a3c4472-689d-11e7-9fe1-bb8627c76421.png)
![2010](https://user-images.githubusercontent.com/30167408/28224510-5a408ad2-689d-11e7-8c86-0376936c375f.png)

**Comment by clauswilke** [comment]
Try setting `stat="density"` in `geom_joy()`. You'll also have to add `height = ..density..` to `aes()`.

**Comment by ggdaniel** [comment]
Awesome! Thank you

![image](https://user-images.githubusercontent.com/30167408/28225210-d13ed83a-689f-11e7-9ae3-f3fa1b364d6d.png)
